import { ChangeDetectionStrategy, Component } from "@angular/core"
import { RouterLink, RouterLinkActive, RouterOutlet } from "@angular/router"

@Component({
  selector: "app-root",
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
  templateUrl: "./app.html",
  styleUrl: "./app.css",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class App {
  protected readonly navigationItems = [
    { label: "Overview", path: "/" },
    { label: "Phase 2 Index", path: "/phase-2" },
    { label: "Phase 3 Index", path: "/phase-3" },
    { label: "WebGL Foundation", path: "/phase-3/webgl-foundation" },
    { label: "WebGL Gradient Triangle", path: "/phase-3/webgl-gradient-triangle" },
    { label: "WebGL Uniform Transform", path: "/phase-3/webgl-uniform-transform" },
    { label: "WebGL Indexed Polygon", path: "/phase-3/webgl-indexed-polygon" },
    { label: "WebGL Texture Grid", path: "/phase-3/webgl-texture-grid" },
    { label: "WebGL Perspective Camera", path: "/phase-3/webgl-perspective-camera" },
    { label: "WebGL Depth Prism", path: "/phase-3/webgl-depth-prism" },
    { label: "WebGL Lit Material", path: "/phase-3/webgl-lit-material" },
    { label: "WebGL Shadow Relief", path: "/phase-3/webgl-shadow-relief" },
    { label: "WebGL Textured Material", path: "/phase-3/webgl-textured-material" },
    { label: "WebGL Dual Pass", path: "/phase-3/webgl-dual-pass" },
    { label: "WebGL Bloom Blur", path: "/phase-3/webgl-bloom-blur" },
    { label: "WebGL Ping-Pong Feedback", path: "/phase-3/webgl-ping-pong-feedback" },
    { label: "WebGL Feedback Trails", path: "/phase-3/webgl-feedback-trails" },
    { label: "WebGL Temporal Feedback", path: "/phase-3/webgl-temporal-feedback" },
    { label: "WebGL Velocity Field", path: "/phase-3/webgl-velocity-field" },
    { label: "WebGL Interactive Dye", path: "/phase-3/webgl-interactive-dye" },
    { label: "WebGL Multi-Obstacle Flow", path: "/phase-3/webgl-multi-obstacle-flow" },
    { label: "WebGPU Foundation", path: "/phase-2/webgpu-foundation" },
    { label: "WebGPU Gradient Quad", path: "/phase-2/webgpu-gradient-quad" },
    { label: "WebGPU Indexed Polygon", path: "/phase-2/webgpu-indexed-polygon" },
    { label: "WebGPU Pulse Diamond", path: "/phase-2/webgpu-pulse-diamond" },
    { label: "WebGPU Uniform Transform", path: "/phase-2/webgpu-uniform-transform" },
    { label: "WebGPU Storage Palette", path: "/phase-2/webgpu-storage-palette" },
    { label: "WebGPU Texture Grid", path: "/phase-2/webgpu-texture-grid" },
    { label: "WebGPU Sampler Wave", path: "/phase-2/webgpu-sampler-wave" },
    { label: "WebGPU Dual Pass", path: "/phase-2/webgpu-dual-pass" },
    { label: "WebGPU Compute Ripple", path: "/phase-2/webgpu-compute-ripple" },
    { label: "WebGPU Instanced Lattice", path: "/phase-2/webgpu-instanced-lattice" },
    { label: "WebGPU Indirect Ribbon", path: "/phase-2/webgpu-indirect-ribbon" },
    { label: "WebGPU Indirect Indexed Polygon", path: "/phase-2/webgpu-indirect-indexed-polygon" },
    { label: "Quadratic Plotter", path: "/algebra/quadratic-plotter" },
    { label: "Derivative Lab", path: "/calculus/derivative-lab" },
    { label: "Integral Lab", path: "/calculus/integral-lab" },
    { label: "Limits Lab", path: "/calculus/limits-lab" },
    { label: "Graph Traversal Lab", path: "/discrete-math/graph-traversal-lab" },
    { label: "Triangle Explorer", path: "/geometry/triangle-explorer" },
    { label: "Payoff Matrix Lab", path: "/game-theory/payoff-matrix-lab" },
    { label: "Unit Circle", path: "/trigonometry/unit-circle" },
    { label: "Sampling Lab", path: "/statistics-probability/sampling-lab" },
    { label: "Distribution Lab", path: "/statistics-probability/distribution-lab" },
    { label: "Vector Explorer", path: "/linear-algebra/vectors" },
    { label: "Euler Characteristic Lab", path: "/topology/euler-characteristic-lab" },
    { label: "Partial Derivatives Lab", path: "/multivariable-calculus/partial-derivatives-lab" },
    { label: "Modular Arithmetic Lab", path: "/number-theory/modular-arithmetic-lab" },
    { label: "Gradient Descent Lab", path: "/optimization/gradient-descent-lab" },
  ]
}
